version: '3.4'

services:
  myhuskyproject:
    image: myhuskyproject
    build:
      context: my-husky-project
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8018:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
