version: '3.4'

services:
  myhuskyproject:
    image: myhuskyproject
    build:
      context: my-husky-project
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8018:3000 
